n ,m  = map(int,input().split())
a = list(map(int,input().split()))
b = list(map(int,input().split()))
s1 = set(a)
s2 = set(b)
giao = sorted(s1 & s2)
hop = sorted(s1-s2)
bu = sorted(s2- s1)
print(' '.join(map(str,giao)))
print(' '.join(map(str,hop)))
print(' '.join(map(str,bu)))
